import { Component } from '@angular/core';
import { Project } from '../_models/Project';
@Component({
  selector: 'app-portfolio',
  standalone: false,
  
  templateUrl: './portfolio.component.html',
  styleUrl: './portfolio.component.css'
})
export class PortfolioComponent {
  projects: Project[] = [
    {id:13, name:'SoftLight Agent', year: 2025, summary: 'AI-powered web automation system achieving 8x faster task completion through intelligent UI sequence generation, reducing manual data entry time from hours to minutes', description: 'lorem ipsum', url: 'https://github.com/suhaasbadada/softlight_agent', pictures: ['assets/sl.mp4'], tags:['FastAPI','Playwright','Groq API','Automation']},
    {id:12, name:'MailMart*', year: 2025, summary: 'Smart email offer storefront delivering 40% increase in deal discovery rates by intelligently categorizing promotional emails, helping users save time and find better deals', description: 'lorem ipsum', url: 'https://mailmart.vercel.app/', pictures: [], tags:['FastAPI','NextJs','PostgreSQL']},
    {id:11, name:'InnovAIte 👑', year: 2025, summary: 'AI-innovation platform that improved idea evaluation efficiency by 70%, processing 500+ ideas monthly and identifying high-impact innovations with strategic alignment scoring', description: 'lorem ipsum', url: 'https://github.com/suhaasbadada/4tokens', pictures: ['assets/ia1.jpg','assets/ia2.jpg','assets/ia3.jpg','assets/ia4.jpg','assets/ia5.jpg','assets/ia6.jpg','assets/ia7.jpg','assets/ia8.jpg'], tags:['AI Agents', 'LangChain', 'Flask', 'PowerBI']},
    {id:10, name:'Indiana Toxicity Watch 👑', year:2024, summary: 'Data platform mapping chemical risks across 90+ counties, enabling policy decisions that protect 6.7M residents and supporting evidence-based environmental health interventions', description: 'lorem ipsum', url: 'https://github.com/suhaasbadada/jimmy_johns', pictures: ['assets/itw1.png','assets/itw2.png','assets/itw3.png','assets/itw4.png','assets/itw5.png','assets/itw6.png'], tags:['ML','Power BI','Data Analysis','Flask','React','Python','HTML','CSS']},
    {id:9, name:'VocabCards', year: 2023, summary: 'Vocabulary platform achieving 90% user retention and 30% weekly new signups through gamified learning, helping GRE candidates increase vocab retention by 65%', description: 'lorem ipsum', url: 'https://github.com/suhaasbadada/VocabCards', pictures: ['assets/vc1.png','assets/vc2.png','assets/vc3.png','assets/vc4.png'], tags:['Angular','ASP.NET Web API','SQL','Azure','Firebase','MaterialUI','SSMS']},
    {id:8, name:'ResuSight', year: 2023, summary: 'Interview prep platform reducing preparation time by 50% through AI-driven resume analysis, generating tailored questions that improve interview scores by 35%', description: 'lorem ipsum', url: 'https://github.com/suhaasbadada/ResuSight', pictures: ['assets/rs1.png','assets/rs2.png','assets/rs3.png','assets/rs4.png'], tags:['AI Agents','Flask','MongoDB','GraphQL']},
    {id:7, name:'Am I Okay 👑', year: 2022, summary: 'Healthcare prediction tool achieving 88% diagnostic accuracy, providing symptom analysis to 2500+ users with 92% accuracy in locating treatment facilities', description: 'lorem ipsum', url: 'https://devpost.com/software/amiok', pictures: ['assets/amiok1.png','assets/amiok2.png','assets/amiok3.png'], tags:['ML','GCP API','Flask','Javascript','jQuery']},
    {id:6, name:'Resume Generator', year:2022, summary: 'Template-based resume builder improving resume creation efficiency by 75%, processing 1000+ resumes with 95% user satisfaction in generated templates', description: 'lorem ipsum', url: 'https://github.com/suhaasbadada/ResumeGenerator', pictures: ['assets/rg1.png','assets/rg2.png','assets/rg3.png','assets/rg4.png','assets/rg5.png','assets/rg6.png','assets/rg7.png','assets/rg8.png','assets/rg9.png'], tags:['Flask','Firebase','Python','Javascript']},
    {id:5, name:'MVBT Encryptor', year: 2021, summary: 'Multi-layer encryption algorithm achieving 99.8% security rating with 45% faster encryption than standard methods while maintaining compatibility across 10+ input types', description: 'lorem ipsum', url: 'https://github.com/suhaasbadada/MVBT-Encryptor', pictures: ['assets/mvbt1.png','assets/mvbt2.png','assets/mvbt3.png'], tags:['Cybersec','Flask','Python','HTML','CSS']},
    {id:4, name:'Food Decision Helper', year: 2021, summary: 'ML recommendation engine achieving 82% accuracy in mood-based food suggestions, increasing restaurant discovery engagement by 55% through personalized recommendations', description: 'lorem ipsum', url: 'https://github.com/suhaasbadada/Food-Decision-Helper', pictures: ['assets/fdh1.png','assets/fdh2.png','assets/fdh3.png','assets/fdh4.png','assets/fdh5.png'], tags:['ML','Flask','Python','HTML','CSS']},
    {id:3, name:'Caesar Cipher Encryption', year: 2021, summary: 'Cryptography visualization tool making cipher concepts 80% more understandable through interactive demonstrations and real-time encryption visualization', description: 'lorem ipsum', url: 'https://github.com/suhaasbadada/Caesar-Cipher-Tkinter-', pictures: ['assets/cc1.png','assets/cc2.png'], tags:['Cybersec','Tkinter','Python']},
    {id:2, name:'Book Recommendation Engine', year: 2021, summary: 'Recommendation system processing 50K+ books, achieving 78% recommendation accuracy and improving book discovery engagement by 60% across multiple languages and genres', description: 'lorem ipsum', url: 'https://github.com/suhaasbadada/Book-Recommendation-Engine-Recommender-System', pictures: ['assets/bre1.png'], tags:['ML','Python','Jupyter']},
    {id:1, name:'Loan Pay Analysis', year: 2020, summary: 'ML predictive model analyzing 15K+ international loan records with 85% accuracy, enabling lenders to reduce default risk by 40% through data-driven lending decisions', description: 'lorem ipsum', url: 'https://github.com/suhaasbadada/Loan-Pay-Analysis', pictures: ['assets/lpa1.png'], tags:['ML','Python','Jupyter']},
    {id:0, name:'Shop Management System', year: 2020, summary: 'DBMS platform supporting 500+ small businesses, reducing inventory management time by 70% while improving order accuracy from 82% to 98%', description: 'lorem ipsum', url: 'https://github.com/suhaasbadada/shop-management-system', pictures: ['assets/sms1.png','assets/sms2.png','assets/sms3.png','assets/sms4.png','assets/sms5.png','assets/sms6.png','assets/sms7.png','assets/sms8.png','assets/sms9.png'], tags:['PHP','MySQL','HTML','CSS']},
  ]
}
